### ISSUE TITLE
Incorrect singular noun for "address" word

### ISSUE THREAD

**Issue by woxcab** [pwdyson/inflect.py#39]
inflect 0.2.5 converts "address" to singular noun incorrectly:
```
import inflect
engine = inflect.engine()
engine.singular_noun("address")
```
outputs `addres` instead of `address`.

**Comment by hugovk** [comment]
> The method singular_noun() takes a plural English noun or pronoun and returns its singular. 

Garbage in, garbage out: you're giving a singular noun when it requires a plural noun.
